param (
    [int]$StartApiPort = 5295,
    [int]$StartWebPort = 8080,
    [int]$StartDbPort = 5432,
    [int]$StartRedisPort = 6379,
    [int]$StartSeqPort = 5341,
    [switch]$SkipBuild
)

function Get-FreePort {
    param ([int]$Port)
    $properties = [System.Net.NetworkInformation.IPGlobalProperties]::GetIPGlobalProperties()
    $listeners = $properties.GetActiveTcpListeners()
    
    while ($listeners.Port -contains $Port) {
        $Port++
    }
    return $Port
}

Write-Host "Horizon FMS - Docker Launcher" -ForegroundColor Cyan
Write-Host "   Finding available ports..." -ForegroundColor Gray

# 1. Resolve Ports
$ApiPort = Get-FreePort -Port $StartApiPort
$WebPort = Get-FreePort -Port $StartWebPort
$DbPort = Get-FreePort -Port $StartDbPort
$RedisPort = Get-FreePort -Port $StartRedisPort
$SeqPort = Get-FreePort -Port $StartSeqPort

# Ensure they aren't the same (basic check)
if ($ApiPort -eq $WebPort) { $WebPort++ }

Write-Host ("   API Port:   " + $ApiPort) -ForegroundColor Green
Write-Host ("   Web Port:   " + $WebPort) -ForegroundColor Green
Write-Host ("   DB Port:    " + $DbPort) -ForegroundColor Green
Write-Host ("   Redis Port: " + $RedisPort) -ForegroundColor Green
Write-Host ("   Seq Port:   " + $SeqPort) -ForegroundColor Green

# 2. Write .env file
$EnvContent = @"
# Generated by start-docker.ps1
API_PORT=$ApiPort
WEB_PORT=$WebPort
DB_PORT=$DbPort
REDIS_PORT=$RedisPort
SEQ_PORT=$SeqPort

POSTGRES_USER=horizon_user
POSTGRES_PASSWORD=horizon_password
POSTGRES_DB=horizon_fms

ASPNETCORE_ENVIRONMENT=Development
ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=horizon_fms;Username=horizon_user;Password=horizon_password;
SEQ_URL=http://seq:5341
REDIS_CONNECTION=redis:6379

# Cloudinary Credentials
CLOUDINARY_CLOUD_NAME=donqnvhzu
CLOUDINARY_API_KEY=529433333387411
CLOUDINARY_API_SECRET=DphttRnx4Q5Vo2KdygkntAPTEvY
"@

$EnvPath = Join-Path (Get-Item $PSScriptRoot).Parent.FullName ".env"
Set-Content -Path $EnvPath -Value $EnvContent
Write-Host "`nUpdated .env configuration." -ForegroundColor Gray

# 3. Run Docker Compose
Write-Host "`nStarting Docker Compose..." -ForegroundColor Cyan
$ProjectRoot = (Get-Item $PSScriptRoot).Parent.FullName
Set-Location $ProjectRoot

if ($SkipBuild) {
    docker-compose up -d
}
else {
    Write-Host "   (Building images to ensure code is up to date...)" -ForegroundColor Gray
    docker-compose up -d --build
}

# 4. Ensure API and Web services are actually started
Write-Host "`nVerifying services..." -ForegroundColor Gray
Start-Sleep -Seconds 2

$apiContainer = docker ps --filter "name=api-service" --format "{{.Names}}"
$webContainer = docker ps --filter "name=web-service" --format "{{.Names}}"

if (-not $apiContainer) {
    Write-Host "   API service not running, attempting to start..." -ForegroundColor Yellow
    docker start (docker ps -a --filter "name=api-service" --format "{{.Names}}")
    Start-Sleep -Seconds 2
}

if (-not $webContainer) {
    Write-Host "   Web service not running, attempting to start..." -ForegroundColor Yellow
    docker start (docker ps -a --filter "name=web-service" --format "{{.Names}}")
    Start-Sleep -Seconds 2
}

Write-Host "`nDocker services started!" -ForegroundColor Green
Write-Host ("   Web: http://localhost:" + $WebPort) -ForegroundColor Cyan
Write-Host ("   API: http://localhost:" + $ApiPort + "/swagger") -ForegroundColor Cyan
Write-Host ("   Seq: http://localhost:" + $SeqPort) -ForegroundColor Cyan
